"""init

Revision ID: 6217e0e20430
Revises: d01b57ad91c0
Create Date: 2025-07-28 18:14:02.232134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6217e0e20430'
down_revision: Union[str, Sequence[str], None] = 'd01b57ad91c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('tg_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('referal', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('whoreferal', sa.String(), nullable=True))
    op.add_column('users', sa.Column('visibility_balance', sa.Boolean(), nullable=True))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'visibility_balance')
    op.drop_column('users', 'whoreferal')
    op.drop_column('users', 'referal')
    op.drop_column('users', 'tg_id')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
