"""init

Revision ID: d01b57ad91c0
Revises: 0ebffe9644b2
Create Date: 2025-07-27 12:30:15.878338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd01b57ad91c0'
down_revision: Union[str, Sequence[str], None] = '0ebffe9644b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('wallet', sa.String(), nullable=True),
    sa.Column('balance', sa.String(), nullable=True),
    sa.Column('pincode', sa.Integer(), nullable=True),
    sa.Column('boolpin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('datatime', sa.String(), nullable=True),
    sa.Column('amount', sa.String(), nullable=True),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('referal', sa.Boolean(), nullable=True),
    sa.Column('whoreferal', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'users_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('users')
    # ### end Alembic commands ###
